services:
  sonali-api:
    image: sonali-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonali-api
    ports:
      - "9090:9090"
    environment:
      - ASPNETCORE_URLS=http://+:9090
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sonali-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
